name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          # NOTE: "latest" = "0.11.1" and "0.11.1" was removed (?)
          purs-tidy: "0.11.0" # "latest"
          spago: "unstable" # "0.93.43" # "next"

      - name: Cache PureScript dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output
            output-es

      - run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true pnpm install --ignore-scripts=true

      - uses: browser-actions/setup-chrome@v1

      - run: CI=true CHROME_BIN="chrome" ./run_headless_tests.sh
